input {
  file {
    path => "/logs/events.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "event"
  }
  file {
    path => "/logs/alerts.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "alert"
  }
  file {
    path => "/logs/audit.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "audit"
  }
  file {
    path => "/logs/fraud-app.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "app-log"
  }
}

filter {
  if [type] == "event" {
    geoip {
      source => "sourceIp"
      target => "geoip"
    }
    date {
      match => ["eventTime", "ISO8601"]
      target => "@timestamp"
    }
    mutate {
      remove_field => ["host", "path", "log", "@version"]
    }
  }
  else if [type] == "alert" {
    date {
      match => ["detectedAt", "ISO8601"]
      target => "@timestamp"
    }
    mutate {
      remove_field => ["host", "path", "log", "@version"]
    }
  }
  else if [type] == "audit" {
    date {
      match => ["evaluatedAt", "ISO8601"]
      target => "@timestamp"
    }
    mutate {
      remove_field => ["host", "path", "log", "@version"]
    }
  }
  else if [type] == "app-log" {
    mutate {
      remove_field => ["host", "path", "log", "@version"]
    }
  }
}

output {
  if [type] == "event" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "events-%{+YYYY.MM}"
      document_id => "%{id}"
    }
  }
  else if [type] == "alert" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "alerts-%{+YYYY.MM}"
      document_id => "%{alertId}"
    }
  }
  else if [type] == "audit" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "audit-%{+YYYY.MM}"
      document_id => "%{auditId}"
    }
  }
  else if [type] == "app-log" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "application-logs-%{+YYYY.MM.dd}"
    }
  }
}
